api_platform:
    title: Leenup API
    description: 'Leenup API documentation'
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    version: 1.0.0

    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        multipart: ['multipart/form-data']

    # ðŸ‘‡ IMPORTANT : on dit Ã  API Platform oÃ¹ chercher les ressources
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/ApiResource'

    # Mercure integration, remove if unwanted
    mercure:
        include_type: true

    # Good defaults for REST APIs
    defaults:
        skip_null_values: false
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

        # Pagination configuration
        pagination_enabled: true
        pagination_items_per_page: 30
        pagination_maximum_items_per_page: 100
        pagination_client_enabled: true
        pagination_client_items_per_page: true
