nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Preload', 'Fields', 'X-CSRF-TOKEN']
        allow_credentials: true
        expose_headers: ['Link', 'X-CSRF-TOKEN']
        max_age: 3600
    paths:
        '^/': null
