vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        profile_avatar:
            uri_prefix: /upload/profile
            upload_destination: '%kernel.project_dir%/public/upload/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
