vich_uploader:
    db_driver: orm

    mappings:
        profile_images:
            uri_prefix: /upload/profile
            upload_destination: '%kernel.project_dir%/public/upload/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
