# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    app.jwt_cookie_secure: '%env(bool:JWT_COOKIE_SECURE)%'
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\State\UserPasswordHasher:
        bind:
            $processor: '@api_platform.doctrine.orm.state.persist_processor'
    
    App\Security\JwtTokenCookieFactory:
        arguments:
            $jwtTtl: '%lexik_jwt_authentication.token_ttl%'
            $cookieSecure: '%app.jwt_cookie_secure%'

    App\Controller\ProfileAvatarUploadController:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\State\Processor\UserSkill\UserSkillProcessor:
        bind:
            $processor: '@api_platform.doctrine.orm.state.persist_processor'
